config/routes.rb
Rails.application.routes.draw do
  #rooting to users#index just to test
  #REMEMBER to change to homepage!
  root to: "users#index"

  resources :users

  get "/sign_in", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: "logout"

  resources :challenges

  get "/users/:user_id/challenges", to: "challenge_users#index", as: "user_challenges"
  post "/challenges/:challenge_id/users", to: "challenge_users#create", as: "challenge_users"
  #get users to show up on challenges

  resources :posts

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	has_many :posts, dependent: :destroy
	
	has_many :challenge_users, dependent: :destroy
	has_many :users, through: :challenge_users

end

app/models/challenge_user.rb
class ChallengeUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :challenge
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :challenge
end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password

	def self.confirm(params)
		@user = User.find_by({email: params[:email]})
		@user.try(:authenticate, params[:password])
	end

	has_many :challenge_users, dependent: :destroy
	has_many :challenges, through: :challenge_users
	has_many :posts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  add_flash_types :error, :success

end

app/controllers/challenge_users_controller.rb
class ChallengeUsersController < ApplicationController

	before_action :logged_in?

	def index
		# @user = User.find(params[:user_id])
		# @challenges = @user.challenges
		@user = User.find(params[:user_id])
		@challenges = @user.challenges
		render :index
		#get users to show up on challenges
		# render :index
	end 

	def create
		@user = current_user
		@challenge = Challenge.find(params[:challenge_id])
		@user_challenge = @user.challenges.push(@challenge)

		redirect_to user_challenges_path(@user)
		#user_challenges(@user) is not working
	end

	def destroy 
		@user = current_user
		@challenge = Challenge.find(params[:challenge_id])
		@user_challenge.destroy
	end

	#change this so that it goes to the user homepage

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController

	before_action :logged_in?

	def index
		@challenges = Challenge.all
		current_user #added this last
		render :index
	end 

	def new
		@challenge = Challenge.new
		render :new
	end 

	def create
		@challenge = Challenge.create(challenge_params)
		@challenge.creator_id = current_user.id 
		@challenge.save!
		@challenge.users.push(current_user)
		redirect_to "/challenges"
	end 

	def show
		@challenge = Challenge.find(params[:id])
		@posts = Post.all

	end 

	def edit
		@challenge = Challenge.find(params[:id])
		if (@current_user.id == @challenge.creator_id)
			render :edit
		else
			redirect_to "/",
				error: "ILLEGAL ACTION"
		end 
	end

	def update
		@challenge = Challenge.find(params[:id])
		@challenge.update_attributes(challenge_params)
		@challenge.save
		redirect_to challenges_path
	end 

	def destroy
		@challenge = Challenge.find(params[:id])
		@challenge.destroy
		redirect_to challenges_path
	end 

	private 

	def challenge_params
		challenge_params = params.require(:challenge).permit(:name, :description, :goal_date, :reward, :img_url, :creator_id)
	end 

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :logged_in?

	def index
		@posts = Post.all
	end 

	def new
		@post = Post.new
		@challenges = Challenge.all
		render :new
	end

	def create
		@post = current_user.posts.new(post_params)
		challenge = @post.challenge_id
		if @post.save
			redirect_to challenge_path(challenge)
		else
			render :new
		end 
	end 

	def show
		@post = Post.find(params[:id])
		@challenge = Challenge.find(@post.challenge_id)
		render :show
	end 

	def edit
		@post = Post.find(params[:id])
		@challenge = Challenge.find(@post.challenge_id)
		if (@current_user == @post.user)
			render :edit
		else
			redirect_to "/",
				error: "ILLEGAL ACTION"
		end 
	end

	def update
		@post = Post.find(params[:id])
		@post.update_attributes(post_params)
		@post.save
		challenge = @post.challenge_id
		redirect_to challenge_path(challenge)
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		challenge = @post.challenge_id
		redirect_to challenge_path(challenge)
	end 

	private

	def post_params
		post_params = params.require(:post).permit(:comment, :picture, :challenge_id)
	end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
		render :new
	end 

	def create
		user_params = params.require(:user).permit(:email, :password)
		@user = User.confirm(user_params)
		if @user
			login(@user)
			redirect_to "/users/#{(@user.id)}"
		else
			redirect_to "/sign_in"
		end 
	end 

	def destroy
		logout
		redirect_to "/"
	end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :logged_in?, except: [:index, :new, :create]

	def index
		@users = User.all
		render :index
	end 

	def new
		@user = User.new
		#might need to change render
		render :new
	end

	def create
		@user = User.create(user_params)
		login(@user)
		redirect_to "/users/#{@user.id}"
	end 

	def show
		@user = User.find(params[:id])
		render :show
	end 

	def edit
		@user = User.find(params[:id])
	end 

	def update 
		@user = User.find(params[:id])
		@user.update_attributes(user_params)
		@user.save
		redirect_to user_path
	end 

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to root_path
	end 

	private

	def user_params
		user_params = params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :img_url)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenge_users_helper.rb
module ChallengeUsersHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def login(user)
		session[:user_id] = user.id
		@current_user = user
	end 

	def current_user
		@current_user ||= session[:user_id] && User.find_by_id(session[:user_id])
	end 

	def logged_in?
		if current_user == nil
			redirect_to "/sign_in"
			#add notice to this
		end 
	end 

	def logout
		@current_user = session[:user_id] = nil
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/challenge_users/index.html.erb
<h4 id="thanks">Thanks for joining a challenge!</h4>


<div class="container" id="challengeinfo">
	<div class="challengeusers">You have <%= @user.challenges.count %> challenge(s)</div>

	<ul>
		<% @challenges.each do |challenge| %>
			<li id="bigtext"><%= challenge.name.upcase %></li>
		<% end %>
	</ul><br><br>
	<%= link_to "Back to Profile", user_path(current_user), :class => 'btn btn-primary'%><br>
</div>

app/views/challenges/_form.html.erb
<div class="col-md-4 col-md-offset-4">
<%= form_for @challenge do |f| %>
	<div>
		<%= f.text_field :name, placeholder: "Name", size: '60x6', required: true %> <sup>*</sup>
	</div>
	<Br>
	<div>
		<%= f.text_field :description, placeholder: "Description", size: '60x20', required: true %> <sup>*</sup>
	</div>
	<Br>
	<div>
		<label id="greytext"> Goal Date </label>
		<%= f.date_select :goal_date, placeholder: "Goal Date", required: true %> <sup>*</sup>
	</div>
	<br>
	<div> 
		<%= f.text_field :reward, placeholder: "Reward for Completing Challange", size: '60x6', required: true %> <sup>*</sup>
	</div><br>
	<%= f.url_field :img_url, placeholder: "Challenge Picture", size: '60x6'%>
	<br>
	<br>
	<sup>*</sup> = required field
	<br>
	<br>
	<%= f.submit :class => "btn btn-primary" %>
	<br>
<% end %>
</div>

app/views/challenges/edit.html.erb
<h1 class="createchallenge">Edit Challenge</h1>

<div class="createform">
	<%= render 'form' %>
</div>

app/views/challenges/index.html.erb
<div>
	<h1 id="h1user">JOIN A CHALLENGE</h1>
</div>

<div class="container">

	<% @challenges.each do |challenge| %>
		  <div id="challengeshow" class="col-xs-4 col-sm-4">
		    <div class="thumbnail">
		      <img id="challengepic1" src="<%= challenge.img_url %>">
					<h3>
					<%= link_to challenge.name.upcase, challenge_path(challenge) %></h3>

				<% if @current_user %>
					<%= button_to "Join", challenge_users_path(challenge), :class => 'btn btn-success' %>
				<% end %>
	     
		      </div>
		    </div>
	<% end %>

</div>

app/views/challenges/new.html.erb
<div class="createchallenge">Create Challenge</div>


<div class="createform">
	<%= render 'form' %>
</div>

app/views/challenges/show.html.erb
<div class="container">

	<h1 id="h1user"><%= @challenge.name.upcase %></h1>

	<div id="challengeinfo" class="col-xs-6 col-md-4">
		<div>
			<img id="challengepic" src="<%= @challenge.img_url %>">
		</div><br>	
		<div><b>Description:</b>
			<%= @challenge.description %>
		</div>
		<div><b>Goal Date:</b> 
			<%= @challenge.goal_date %>
		</div>
		<div><b>Reward:</b> 
			<%= @challenge.reward %>
		</div><Br>

	<%= link_to "Leave Challenge", @challenge_users, :method => :delete, :class => 'btn btn-danger' %><br><Br>

	<% if @current_user %>
					<%= button_to "Join Challenge", challenge_users_path(@challenge), :class => 'btn btn-success' %>
				<% end %>
	<br>


	<% if current_user && current_user.id == @challenge.creator_id %>

		<%= link_to "Edit Challenge", edit_challenge_path(@challenge), :method => :get, :class => 'btn btn-primary'%>

		<%= link_to "Delete Challenge", @challenges, method: :delete, :class => 'btn btn-danger'%>

	<% end %>
	<Br>
	<br>
	<h1 class="posttitle members">Members in this Challenge</h1>

		<% @challenge.users.each do |u| %>
			<div class="members">
				<%= u.first_name %>
			</div>
		<% end %>

	</div>


	<div class="col-xs-12 col-md-8" id="postbody">
		<h1 class="posttitle">Discussion Board</h1>

			<div>
				<%= link_to "Create a Post", new_post_path, :class => 'btn btn-success' %>
			</div>
		<br><br>

		<% @challenge.posts.each do |post| %>
			<!-- <div class="post col-xs-6 col-md-4"> -->
				<!-- <img id="postpic" src="<%= post.picture %>"/><br><Br> -->
					<div class="postcomment">
						<b id="poststyle"><%= post.user.first_name.upcase %></b>: <%= link_to post.comment, post_path(post), :class => 'postlink' %><br>
					<!-- </div> -->
			</div>
		<% end %> 
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChallengeApp</title>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Michroma' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>

</head>
<header class='clearfix'>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				 <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
		      	</button>
	      	<a class="navbar-brand" id="brveicon" href="/">BRVE</a>
    	</div>
		

		 <div class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<% if not current_user %>
			<div>
				<ul class="nav navbar-nav navbar-right">
				<li class="homelink"><%= link_to "SIGN UP", new_user_path %></li>
				<li class="homelink" id="SO"><%= link_to "LOGIN", sign_in_path %></li>
				</ul>
			</div>
			<% else %>
			<div>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "#{current_user.first_name.upcase}", user_path(current_user) %></li>
					<li><%= link_to "CHALLENGES", challenges_path %></li>
				  	<li id="AC"><%= link_to "ADD CHALLENGE", new_challenge_path %></li>
				 	<li id="SO"><%= link_to "SIGN OUT", logout_path, :method => :delete %></li>
				</ul>
			</div>
			<% end %>
		</div>
		</div> <!-- container fluid -->
	</nav>
</header>

<body>

<article>
	<%= yield %>
</article>
 

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/posts/edit.html.erb
<h1 id="h1user"><%= @challenge.name %></h1>

<div class="createform">
	<%= form_for @post do |f| %>
		<div>
			<%= f.text_field :comment, placeholder: "Comment", required: true, size: '60x6', :class => 'forminput' %> <sup>*</sup>
		</div>
		<br>
		<div>
			<%= f.url_field :picture, placeholder: "Picture URL", size: '60x6', :class => 'forminput' %>
		</div>
		<br>
		<br>
		<sup>*</sup> = required field
		<br>
		<br>
		<%= f.submit :class => 'btn btn-success' %>
	<% end %>
</div>

app/views/posts/new.html.erb
<h1 id="h1user">Add a Post</h1>

<div class="createform">
	<%= form_for @post do |f| %>
		<div>
			<%= f.text_field :comment, placeholder: "Comment", required: true, size: '60x6' %> <sup>*</sup>
		</div>
		<br>
		<p id="greytext">Select Challenge:</p>
		<div>
			<%= f.collection_select :challenge_id, @challenges, :id, :name %> <sup>*</sup>
		</div>
		<br>
		<br>
		<sup>*</sup> = required field
		<br>
		<br>
		<%= f.submit :class => 'btn btn-success' %>
	<% end %>
</div>

app/views/posts/show.html.erb
<h1 id="h1user"><%= @challenge.name %></h2>


<div class="createform">
<b id="poststyle"><%= @post.user.first_name.upcase %> said:</b> <%= @post.comment %><br>
<img src="<%= @post.picture %>"/>
<Br><br>
<% if current_user && current_user.id == @post.user_id %>
	<%= button_to "Edit Post", edit_post_path(@post), :method => :get, :class => 'btn btn-primary' %><br>
	<%= button_to "Delete Post", @post, :method => :delete, :class => 'btn btn-danger'%>
<% end %>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<div>
		<%= f.text_field :first_name, placeholder: "First Name", required: true, size: '60x6' %> <sup>*</sup>
	</div>
	<br>
	<div>
		<%= f.text_field :last_name, placeholder: "Last Name", required: true, size: '60x6' %> <sup>*</sup>
	</div>
	<br>
	<div>
		<%= f.email_field :email, placeholder: "Email", required: true, size: '60x6' %> <sup>*</sup>
	</div>
	<br>
	<div>
		<%= f.password_field :password, placeholder: "Password", required: true, size: '60x6' %> <sup>*</sup>
	</div>
	<br>
	<div>
		<%= f.password_field :password_confirmation, placeholder: "Confirm Password", required: true, size: '60x6' %> <sup>*</sup>
	</div>
	<Br>
		<%= f.url_field :img_url, placeholder: "Profile Picture", size: '60x6'%>
	<Br>
	<br>
	<sup>*</sup> = required field
	<br>
	<br>
	<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/users/edit.html.erb
<h1 id="h1user">Edit User</h1>

<div id="edituser">
	<%= render 'form' %>
</div>

<br> <div id="deleteuser">
<%= link_to "Delete User", @user, method: :delete, :class => 'btn btn-danger' %>
</div>

app/views/users/index.html.erb
<div class="flash">
<%= error %>
</div>


<div id="brvehomepage">
	<h1 id="brvename">BRVE</h1>
	<p id="quote">IF THEY CAN DO IT, SO CAN YOU</p>
</div>

app/views/users/new.html.erb
<h1 id="h1user">Create an Account</h1>


<div id="newuser">
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container">	
	<div id="userinfo" class="col-xs-6 col-md-4">
		<div class="userhome">
			Welcome, <b id="username"><%= @user.first_name %></b>
		</div>


		<div class="profileinfo">
			<div class="profileimg">
				<img id="profilepic" src="<%= @user.img_url %>">
			</div>
			<br>

			<p id="stats"><b><%= @user.first_name %> <%= @user.last_name %>'s Stats</b></p>

			<p> Upcoming Challenges: <span class="badge"><%= @user.challenges.count %></span> </p>
			<p> Number of Posts: <span class="badge"><%= @user.posts.count %></span> </p><br>

			<%= link_to "Edit Profile", edit_user_path(current_user), :class => 'btn btn-primary'%>
			<br>
			<Br>
			<br>
			<p id="instructions">
				<h3>What you can do:</h3><br>
					<%= link_to "Create", new_challenge_path %> your own Challenge<Br>
					Join/Leave a Challenge<br>
					Comment on a Challenge Page
			</p>
		</div>
	</div>


	<div id="userchallenges" class="col-xs-12 col-md-8">

		<p id="upcoming">CURRENT CHALLENGES</p>
		<br>

		<div class="container">

		<% @user.challenges.each do |challenge| %>
			<div>
			  <div class="col-sm-5 col-md-6">
			  <a href="<%= challenge_path(challenge) %>">
			    <div class="thumbnail grow">
				      <img id="challengepic1" src="<%= challenge.img_url %>">
				      <p class="text"><%= challenge.description %></p>
				      	<h4 class="createform">
				        <%= link_to challenge.name, challenge_path(challenge) %></h4>
			      </div>
			    </div>
			  </div>
		<% end %> 
	</div>
</div>